### ISSUE TITLE
remove weight normalization at inference phase

### ISSUE THREAD

**Issue by seungwonpark** [seungwonpark/melgan#16]
I'm thinking of writing some code snippet to remove weight normalization of `pt` file, and remove discriminator components to make the checkpoint file smaller.

**Comment by Liujingxiu23** [comment]
@seungwonpark  is the output  with or without remove_weight_norm is the same?

I use melgan scripts https://github.com/descriptinc/melgan-neurips and following your way to remove the weight norm parameters. But the output differs from the original outputs.
