### ISSUE TITLE
How about the inference speed?

### ISSUE THREAD

**Issue by auzxb** [seungwonpark/melgan#20]
Thanks for your implementation of MelGan. As is introduced, MelGAN is lighter, faster, and better at generalizing speech. How about the inference speed?

**Comment by seungwonpark** [comment]
The authors stated that both training/inference speed is faster than previous SotA, WaveGlow.

I haven't measured the exact inference speed, but I could observe MelGAN working really fast on my desktop PC with GTX 1050.

**Comment by auzxb** [comment]
Really nice!

**Comment by xxoospring** [comment]
> The authors stated that both training/inference speed is faster than previous SotA, WaveGlow.
> 
> I haven't measured the exact inference speed, but I could observe MelGAN working really fast on my desktop PC with GTX 1050.

have you ever experiment it on cpu only machine?

**Comment by seungwonpark** [comment]
Yes, but I still recommend to use GPU. Not fast enough to be real-time on CPU.
