### ISSUE TITLE
Wrong implementation of Generator

### ISSUE THREAD

**Issue by seungwonpark** [seungwonpark/melgan#22]
The last layer should be:
```python
nn.utils.weight_norm(nn.Conv1d(32, 1, kernel_size=7, stride=1, padding=3)),
```

not:
```python
nn.utils.weight_norm(nn.ConvTranspose1d(32, 1, kernel_size=7, stride=1, padding=3)),
```

omg...

**Comment by seungwonpark** [comment]
Working on this at `fix/22` branch.

I'll be training the model from scratch and upload audio samples again. I wonder why the previous model was working well.

**Comment by bob80333** [comment]
As far as why it worked so well, [this article](https://towardsdatascience.com/is-the-transposed-convolution-layer-and-convolution-layer-the-same-thing-8655b751c3a1) trains a CNN image classifier with Conv2d and ConvTranspose2d using the same hyperparameters for both and gets almost identical results.

**Comment by seungwonpark** [comment]
The new version looks working well. I will merge it to `master` branch after the pre-trained model is ready. Also, will update the audio samples.
