### ISSUE TITLE
직접 학습한 타코트론2에 적용해 봤는데 끝에 소리가 끊어지네요

### ISSUE THREAD

**Issue by gateoneh92** [seungwonpark/melgan#23]
혹시 이유를 아시나요?
[epoch1750.wav.zip](https://github.com/seungwonpark/melgan/files/3823500/epoch1750.wav.zip)

**Comment by seungwonpark** [comment]
이건 tacotron2 부분의 문제인 것 같습니다. mel-spectrogram을 한번 plot 해보시길 추천드립니다.
