### ISSUE TITLE
Augmentation 

### ISSUE THREAD

**Issue by m-toman** [seungwonpark/melgan#24]
Hi,
I've noticed you add random noise to the audio. I just wondered if it would make more sense to add random noise to the Mel spectra? Considering that this is what you might get from something like tacotron, so noisy mels.

**Comment by seungwonpark** [comment]
Hi, actually I didn't intend to augment the data by adding random noise to audio. I wanted to make sure that discriminator doesn't learn that raw audios with real values are fake, and discrete values from `int16` are real.

**Comment by m-toman** [comment]
Ah, cool trick. I've seen in the official implementation they randomly vary the amplitude a bit and call it "augment", that's why I was asking (https://github.com/descriptinc/melgan-neurips/blob/master/mel2wav/dataset.py#L66-L68)

Actually I'm currently investigating that even GTA data from Tacotron seems to be quite different from actual (non-teacher-fed) data. And my first intention was to generate GTA data multiple times - assuming that because of the huge Tacotron dropout used during inference they would also differ significantly between runs, but I'll have to confirm this first.

Then I remembered this augment thing and that I saw you using random noise.

**Comment by seungwonpark** [comment]
That sounds insightful. Unfortunately, I couldn't do that kind of data augmentation since the mel-spectrograms are pre-processed at first.

I'm not sure whether MelGAN is robust against the discrepancy between ground-truth & tacotron2-generated mel-spectrogram. Could you please let me know if you get insight into this?

**Comment by m-toman** [comment]
I have the same problem with the preprocessing, especially with the GTA mels of course, that I can't do this type of augmentation.

I'm currently training with the official implementation on GTA data but it still sounds a bit raspy and has a couple artefacts in it (epoch 1300 atm) in the actual synthesis (running the vocoder on the GTA features sounds much better).

That's why I'm thinking about approaches to deal with noisier spectra than the ones it sees during training. Perhaps just training from multiple speakers would help as well.

**Comment by m-toman** [comment]
At the moment it seems adding your noise did help, but perhaps it was just the additional night of training ;).
Although sometimes taco still generates mels that result in a raspy voice, running in a second time usually "solves" it.

**Comment by seungwonpark** [comment]
Sounds great. Shall we close this issue?

**Comment by m-toman** [comment]
Yeah I'll report back if something useful comes up :)
