### ISSUE TITLE
erro in inference

### ISSUE THREAD

**Issue by li-xx-5** [seungwonpark/melgan#25]
hello.when i run inference.py, i met this erro.
0it [00:00, ?it/s]
how can i solve that?thank you

**Comment by seungwonpark** [comment]
Your input path should contain at least one mel-spectrogram file in *.mel format.

**Comment by li-xx-5** [comment]
@seungwonpark
I have changed the.mel file to.png file in the inference.  but the problem still appears.like this,because my mel file is step210000_predicted_spectrogram.png.

for melpath in tqdm.tqdm(glob.glob(os.path.join(args.input_folder, '*.png'))):
            mel = torch.load(melpath)
            if len(mel.shape) == 2:
                mel = mel.unsqueeze(0)
            mel = mel.cuda()

**Comment by li-xx-5** [comment]
@ seungwonpark
Do I have to use the.mel file format？

**Comment by seungwonpark** [comment]
Image files are not a valid representation of the mel-spectrogram. They're visualization. They can't be an input for this network.
