### ISSUE TITLE
Click sound artifact at the end of each sample

### ISSUE THREAD

**Issue by seungwonpark** [seungwonpark/melgan#8]
At each resulting audio sample, there are audible clicking sound at the end.
This is also visible at the raw audio visualization in tensorboard.

Target:
![image](https://user-images.githubusercontent.com/13394294/67455017-2a1b3000-f667-11e9-9936-15cc43f26699.png)

Predicted:
![image](https://user-images.githubusercontent.com/13394294/67455053-474ffe80-f667-11e9-9cff-1c10b9eb353f.png)

**Comment by seungwonpark** [comment]
Subtracting the result of zero-filled mel-spectrogram can reduce the noise, but not perfectly.
(This was also done by NVIDIA/waveglow.)
![image](https://user-images.githubusercontent.com/13394294/67455712-6f406180-f669-11e9-95c2-6706c8a5316a.png)

The second row shows the waveform of result from zero-filled(tensor tiled with `-11.5129`) mel spectrogram.

**Comment by seungwonpark** [comment]
Oh wait, this was not a way that NVIDIA/waveglow used to denoise.

**Comment by seungwonpark** [comment]
Spectrogram of reconstructed audio.
Something in the right side is visible.

Reconstructed:
![image](https://user-images.githubusercontent.com/13394294/67456629-5dac8900-f66c-11e9-9e13-d2c6ae984fdd.png)

Target:
![image](https://user-images.githubusercontent.com/13394294/67456676-7d43b180-f66c-11e9-8d95-9c505d4f13b8.png)

**Comment by seungwonpark** [comment]
I think the best solution is to concat few zero-valued(actually, -11.5129) mel-spectrogram frames, infer, and then cut the end.

**Comment by G-Wang** [comment]
@seungwonpark I think add zeros and fading out at the end is indeed something that could alleviate the clicking. For example with Fatcord's WaveRNN here:  https://github.com/fatchord/WaveRNN/blob/12922a780f0d65a4572f6de27f33ec8f3189cfe8/models/fatchord_version.py#L255

**Comment by rishikksh20** [comment]
Both solutions are very good and must be implemented for quality sound, but my interest is somehow we can manage to eliminate this kind of noise at the Neural network level (`R&D thing`) or some way to model this noise. This will helps to train a robust Network and understand the hidden gems to make it more controllable though it is not a big concern. Like to know your views on this @seungwonpark @G-Wang.
>Meanwhile I noticed that this repo generated samples are better than original ones posted by authors of the paper at the same checkpoint.

**Comment by G-Wang** [comment]
@rishikksh20 I would think adding a few silent mel frames to the end of each mel in the training data would let the model learn to add longer silences to the end?

could you link the best numpy synthesised audio files from your 1600 + epoch model? I'll see if fading out the end helps with the clicking artifacts

**Comment by rishikksh20** [comment]
@G-Wang check out here: https://drive.google.com/drive/folders/1iOhMO1qjfVwgJjyPN8G4iwM-bFCuxWiM?usp=sharing
I have tried fade-out thing you can check samples at `fade-out sample` folder and `samples` folder have original without fade-out sample. Even after fade-out thing still very small a kind of unnoticeable artifact remains at end. Samples generated at 2400 epochs.

**Comment by rishikksh20** [comment]
> Oh wait, this was not a way that NVIDIA/waveglow used to denoise.

@seungwonpark have you tried waveglow's denoiser, as I see they implement a denoiser seperate from waveglow and just apply after inference from waveglow. I will try to use their denoiser and it here, it might remove some extra noises and return complete background silent sample.

**Comment by rishikksh20** [comment]
I have implemented waveglow denoiser in this repo, and sample is uploded to `waveglow_denoiser` folder here: https://drive.google.com/drive/folders/1iOhMO1qjfVwgJjyPN8G4iwM-bFCuxWiM?usp=sharing

**Comment by seungwonpark** [comment]
I doubt we'll need waveglow denoiser for this repo since the type of noise is different here, but thanks anyway. (Refer to https://github.com/NVIDIA/waveglow/issues/55)

I think it's issue of `datasets/dataloder.py` instead of NN.
https://github.com/seungwonpark/melgan/blob/master/datasets/dataloader.py#L52-L59

To cover all samples in raw audio domain, the maximal value of `audio_start` should be 
`audio.size(1)-self.hp.audio.segment_length`. However, to match mel and audio, it became `(max_mel_start-1)*self.hp.audio.segment_length`, which is always smaller or equal to `audio.size(1)-self.hp.audio.segment_length`. This makes NN to not see very last part of audio, which may lead to artifact.

**Comment by seungwonpark** [comment]
I think we have two choices:

1. Zero-pad the end of `audio` in `my_getitem(self, idx)` during training
2. Fade-out or pad the end of `mel`, and cut during inference

**Comment by seungwonpark** [comment]
btw I noticed another kind of artifact at the end, which is pretty long.
Those are audios from http://swpark.me/melgan/.
![image](https://user-images.githubusercontent.com/13394294/67540205-89d51200-f71f-11e9-8327-f01ed5681dc0.png)

**Comment by rishikksh20** [comment]
@seungwonpark It looks like the problem with modeling silence I think if we train more it goes down otherwise if a similar kind artifact occurs when generating audio from zero-filled mels if so we can use that as noise profile and eliminate this using any noise reducer.

**Comment by seungwonpark** [comment]
That sounds reasonable. I also found similar artifacts not only in the last part but also in the middle.

![image](https://user-images.githubusercontent.com/13394294/67540747-804ca980-f721-11e9-9a50-760a204ca674.png)
